data:
  input:
    text_dir: "data/input/text/"
    images_dir: "data/input/images/"
  output: "data/output"

spacy:
    model: "en_core_web_lg"

evaluation:
    enabled: true
    #scenarios: ["high-precision", "moderate-connectivity", "comprehensive"]
#    scenarios: ["dev_a_precision", "dev_b_balanced", "dev_c_diverse"]
    scenarios: ["dev_a_precision"]
    runs_per_algorithm: 1
    metrics:
      - "total_time"
      - "throughput"
      - "success_rate"
      - "processing_overhead"
      - "conflicts"
      - "memory_peak"
      - "cpu_avg"
    output_dir: "data/evaluation/"

database:
  neo4j:
    uri: "bolt://localhost:7687"
    user: "neo4j"
    password: "research123"
    database: "research"


algorithms:
  sequential:
    name: "Sequential insertion (no parallelization)"
    batch_size: 1000

  naive_parallel:
    name: "Naive parallelization (no conflict detection)"
    batch_size: 1000
    thread_count: 6
    max_retries: 99999

  mix_and_batch:
    name: "Heuristic approach: Mix and Batch"
    num_partitions: 10
    thread_count: 6
    batch_size: 1000
    hash_digits: 1
    max_retries: 999

  apoc:
    name: "Parallelization with APOC Procedures"
    batch_size: 1000
    thread_count: 6  # Initial threads
    max_retries: 9999


  color_batch:
    name: "Color Batch Insert"
    thread_count: 6
    batch_size: 1000
