data:
  input:
    text_dir: "data/input/text/"
    images_dir: "data/input/images/"
  output: "data/output"

spacy:
    model: "en_core_web_lg"

evaluation:
    enabled: true
    scenarios: ["s1","s2","s3"]
    runs_per_algorithm: 3
    metrics:
      - "total_time"
      - "throughput"
      - "success_rate"
      - "processing_overhead"
      - "conflicts"
      - "memory_peak"
      - "cpu_avg"
    output_dir: "data/evaluation/"

database:
  neo4j:
    uri: "bolt://localhost:7687"
    user: "neo4j"
    password: "research123"
    database: "research"

algorithms:

  sequential:
    name: "Sequential insertion"
    batch_size: 1000
    thread_count: 1

  naive_parallel:
    name: "Naive parallelization"
    batch_size: 1000
    thread_count: 14
    max_retries: 999999

  mix_and_batch:
    name: "Mix and Batch"
    batch_size: 1000
    num_partitions: 10
    thread_count: 14
    hash_digits: 1
    max_retries: 999999

  apoc:
    name: "APOC Parallel"
    batch_size: 1000
    thread_count: 14
    max_retries: 9999999

  sapoc:
    name: "Sequential APOC"
    batch_size: 1000
    thread_count: 1
    max_retries: 9999999

  color_batch:
    name: "Color Batch Insert"
    batch_size: 1000
    thread_count: 14
